from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from typing import List, Any
from uuid import UUID
import json

from app.db.session import get_db
from app.api.deps import get_current_user
from app.models.user import User
from app.models.agent_models import KnowledgeGraphNode, KnowledgeGraphRelation
from app.schemas.agents import (
    TaskCreate, TaskResponse, KnowledgeGraphResponse, ReportResponse, 
    GraphNodeResponse, GraphRelationResponse, GraphNodeCreate, 
    GraphNodeUpdate, GraphRelationCreate, EntityExtractionRequest, ExtractionResponse
)
from app.services.agent_service import AgentService
from app.repositories.agent_repo import AgentRepository

router = APIRouter()

@router.post("/task", response_model=Any, status_code=status.HTTP_201_CREATED)
def trigger_workspace_agent_task(
    payload: TaskCreate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
) -> Any:
    """
    Triggers execution of a specific Multi-Agent workflow in the project workspace:
    - Supported task_types: 'literature_review', 'knowledge_graph', 'trend_analysis', 'research_proposal', 'fact_check'
    """
    try:
        service = AgentService(db)
        response = service.trigger_agent_task(payload)
        return response
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Agent workflow execution failed: {str(e)}"
        )


@router.get("/project/{project_id}/tasks", response_model=List[TaskResponse])
def get_project_agent_tasks(
    project_id: UUID,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
) -> Any:
    """
    Retrieves execution histories and outputs of all agent tasks triggered in the project workspace.
    """
    try:
        repo = AgentRepository(db)
        return repo.get_tasks_by_project(project_id)
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to fetch tasks: {str(e)}"
        )


@router.get("/project/{project_id}/graph", response_model=KnowledgeGraphResponse)
def get_project_knowledge_graph(
    project_id: UUID,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
) -> Any:
    """
    Retrieves the complete semantic Knowledge Graph (nodes & connections) extracted by the multi-agent graph layer.
    """
    try:
        repo = AgentRepository(db)
        nodes, relations = repo.get_project_graph(project_id)
        
        # Format lists using response models
        nodes_res = [GraphNodeResponse.model_validate(n) for n in nodes]
        relations_res = [GraphRelationResponse.model_validate(r) for r in relations]
        
        return KnowledgeGraphResponse(nodes=nodes_res, relations=relations_res)
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to compile knowledge graph: {str(e)}"
        )


@router.get("/project/{project_id}/reports", response_model=List[ReportResponse])
def get_project_reports(
    project_id: UUID,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
) -> Any:
    """
    Retrieves all reports (literature reviews, grant proposals, gap analyses) generated by the multi-agent system.
    """
    try:
        repo = AgentRepository(db)
        return repo.get_reports_by_project(project_id)
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to retrieve reports: {str(e)}"
        )


@router.post("/project/{project_id}/nodes", response_model=GraphNodeResponse, status_code=status.HTTP_201_CREATED)
def create_project_node(
    project_id: UUID,
    payload: GraphNodeCreate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
) -> Any:
    """
    Manually creates a new node in the interactive knowledge graph.
    """
    try:
        repo = AgentRepository(db)
        payload.project_id = project_id
        node = repo.get_or_create_node(payload)
        return GraphNodeResponse.model_validate(node)
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to create node: {str(e)}"
        )


@router.put("/project/{project_id}/nodes/{node_id}", response_model=GraphNodeResponse)
def update_project_node(
    project_id: UUID,
    node_id: UUID,
    payload: GraphNodeUpdate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
) -> Any:
    """
    Updates label, type, or properties of an existing node.
    """
    try:
        node = db.query(KnowledgeGraphNode).filter(
            KnowledgeGraphNode.project_id == project_id,
            KnowledgeGraphNode.id == node_id
        ).first()
        if not node:
            raise HTTPException(status_code=404, detail="Node not found")
        
        if payload.label is not None:
            node.label = payload.label
        if payload.type is not None:
            node.type = payload.type
        if payload.properties is not None:
            node.properties = payload.properties
            
        db.add(node)
        db.commit()
        db.refresh(node)
        return GraphNodeResponse.model_validate(node)
    except HTTPException as he:
        raise he
    except Exception as e:
        db.rollback()
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to update node: {str(e)}"
        )


@router.delete("/project/{project_id}/nodes/{node_id}", status_code=status.HTTP_200_OK)
def delete_project_node(
    project_id: UUID,
    node_id: UUID,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
) -> Any:
    """
    Deletes an existing node and automatically cascades deleting all connecting links.
    """
    try:
        node = db.query(KnowledgeGraphNode).filter(
            KnowledgeGraphNode.project_id == project_id,
            KnowledgeGraphNode.id == node_id
        ).first()
        if not node:
            raise HTTPException(status_code=404, detail="Node not found")
        
        db.delete(node)
        db.commit()
        return {"status": "success", "message": "Node and cascading relationships deleted"}
    except HTTPException as he:
        raise he
    except Exception as e:
        db.rollback()
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to delete node: {str(e)}"
        )


@router.post("/project/{project_id}/relations", response_model=GraphRelationResponse, status_code=status.HTTP_201_CREATED)
def create_project_relation(
    project_id: UUID,
    payload: GraphRelationCreate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
) -> Any:
    """
    Manually creates a new directed semantic relation between two existing nodes.
    """
    try:
        repo = AgentRepository(db)
        payload.project_id = project_id
        relation = repo.create_relation(payload)
        return GraphRelationResponse.model_validate(relation)
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to create relationship: {str(e)}"
        )


@router.delete("/project/{project_id}/relations/{relation_id}", status_code=status.HTTP_200_OK)
def delete_project_relation(
    project_id: UUID,
    relation_id: UUID,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
) -> Any:
    """
    Deletes an existing directed semantic relation between two nodes.
    """
    try:
        relation = db.query(KnowledgeGraphRelation).filter(
            KnowledgeGraphRelation.project_id == project_id,
            KnowledgeGraphRelation.id == relation_id
        ).first()
        if not relation:
            raise HTTPException(status_code=404, detail="Relationship not found")
        
        db.delete(relation)
        db.commit()
        return {"status": "success", "message": "Relationship deleted"}
    except HTTPException as he:
        raise he
    except Exception as e:
        db.rollback()
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to delete relationship: {str(e)}"
        )


@router.post("/project/{project_id}/extract", response_model=ExtractionResponse)
def extract_entities_from_text(
    project_id: UUID,
    payload: EntityExtractionRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
) -> Any:
    """
    Performs automated Entity and Relation Extraction on raw user-provided text using Gemini AI,
    installs them in the project workspace, and returns the compiled topology.
    """
    try:
        repo = AgentRepository(db)
        from app.core.config import settings
        api_key = settings.GEMINI_API_KEY
        
        nodes_res = []
        relations_res = []
        extracted_data = {"nodes": [], "relations": []}
        
        if api_key and api_key != "MY_GEMINI_API_KEY":
            try:
                from google import genai
                from google.genai import types
                
                client = genai.Client(api_key=api_key)
                
                prompt = (
                    "Extract key entities and their semantic relationships from the following text:\n\n"
                    f"\"\"\"{payload.text}\"\"\"\n\n"
                    "Identify important concepts, methodologies, datasets, technologies, institutions, or other key elements as nodes.\n"
                    "Then, map the relations (edges) between these nodes.\n\n"
                    "You MUST respond ONLY with a valid JSON object matching this schema. Do not include markdown formatting, backticks, or wrapping except the raw JSON string itself:\n"
                    "{\n"
                    "  \"nodes\": [\n"
                    "    { \"label\": \"Entity Name\", \"type\": \"Methodology|Dataset|Technology|Institution|Concept|Metric\", \"properties\": { \"description\": \"...\" } }\n"
                    "  ],\n"
                    "  \"relations\": [\n"
                    "    { \"source_label\": \"Source Entity Name\", \"source_type\": \"Source Entity Type\", \"target_label\": \"Target Entity Name\", \"target_type\": \"Target Entity Type\", \"relation_type\": \"INFLUENCES|UTILIZES|EVALUATED_ON|PRODUCES|CONTAINS|PART_OF|ASSOCIATED_WITH\", \"properties\": {} }\n"
                    "  ]\n"
                    "}"
                )
                
                response = client.models.generate_content(
                    model='gemini-2.5-flash',
                    contents=[prompt]
                )
                text_response = response.text.strip()
                
                if text_response.startswith("```json"):
                    text_response = text_response[7:]
                if text_response.startswith("```"):
                    text_response = text_response[3:]
                if text_response.endswith("```"):
                    text_response = text_response[:-3]
                text_response = text_response.strip()
                
                extracted_data = json.loads(text_response)
            except Exception as gemini_err:
                print(f"Gemini Extraction failed: {gemini_err}")
                extracted_data = _local_fallback_extraction(payload.text)
        else:
            extracted_data = _local_fallback_extraction(payload.text)
            
        # Process and save extracted nodes
        for n in extracted_data.get("nodes", []):
            try:
                node_in = GraphNodeCreate(
                    project_id=project_id,
                    label=n.get("label", "Unknown")[:100],
                    type=n.get("type", "Concept")[:50],
                    properties=n.get("properties", {})
                )
                node_obj = repo.get_or_create_node(node_in)
                nodes_res.append(GraphNodeResponse.model_validate(node_obj))
            except Exception as ne:
                print(f"Failed to process extracted node {n}: {ne}")
                
        # Process and save extracted relations
        for r in extracted_data.get("relations", []):
            try:
                src_label = r.get("source_label", "Unknown")[:100]
                src_type = r.get("source_type", "Concept")[:50]
                tgt_label = r.get("target_label", "Unknown")[:100]
                tgt_type = r.get("target_type", "Concept")[:50]
                
                src_node_in = GraphNodeCreate(project_id=project_id, label=src_label, type=src_type, properties={})
                src_obj = repo.get_or_create_node(src_node_in)
                if src_obj.id not in [n.id for n in nodes_res]:
                    nodes_res.append(GraphNodeResponse.model_validate(src_obj))
                
                tgt_node_in = GraphNodeCreate(project_id=project_id, label=tgt_label, type=tgt_type, properties={})
                tgt_obj = repo.get_or_create_node(tgt_node_in)
                if tgt_obj.id not in [n.id for n in nodes_res]:
                    nodes_res.append(GraphNodeResponse.model_validate(tgt_obj))
                    
                rel_in = GraphRelationCreate(
                    project_id=project_id,
                    source_node_id=src_obj.id,
                    target_node_id=tgt_obj.id,
                    relation_type=r.get("relation_type", "ASSOCIATED_WITH")[:50],
                    properties=r.get("properties", {})
                )
                rel_obj = repo.create_relation(rel_in)
                relations_res.append(GraphRelationResponse.model_validate(rel_obj))
            except Exception as re:
                print(f"Failed to process extracted relation {r}: {re}")
                
        return ExtractionResponse(nodes=nodes_res, relations=relations_res)
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Automated extraction failed: {str(e)}"
        )


def _local_fallback_extraction(text: str) -> dict:
    import re
    text_lower = text.lower()
    
    nodes = []
    relations = []
    
    methodology_matches = re.findall(r'\b(machine learning|deep learning|neural network|transformer|gcn|cnn|transformer|bert|gpt|regression|clustering)\b', text_lower)
    dataset_matches = re.findall(r'\b(mnist|imagenet|arxiv|wikipedia|coco|csv|dataframe|database|sql)\b', text_lower)
    technology_matches = re.findall(r'\b(pytorch|tensorflow|python|node|d3|react|postgres|docker)\b', text_lower)
    
    methodology_matches = list(set(methodology_matches))
    dataset_matches = list(set(dataset_matches))
    technology_matches = list(set(technology_matches))
    
    for m in methodology_matches:
        nodes.append({"label": m.title(), "type": "Methodology", "properties": {"extracted": "heuristic"}})
    for d in dataset_matches:
        nodes.append({"label": d.upper() if len(d) <= 5 else d.title(), "type": "Dataset", "properties": {"extracted": "heuristic"}})
    for t in technology_matches:
        nodes.append({"label": t.title() if t != "d3" else "D3.js", "type": "Technology", "properties": {"extracted": "heuristic"}})
        
    if not nodes:
        nodes.append({"label": "Core Subject", "type": "Concept", "properties": {"description": "Heuristic fallback entity"}})
        nodes.append({"label": "Secondary Variable", "type": "Concept", "properties": {"description": "Associated entity"}})
        relations.append({
            "source_label": "Core Subject", "source_type": "Concept",
            "target_label": "Secondary Variable", "target_type": "Concept",
            "relation_type": "ASSOCIATED_WITH", "properties": {}
        })
    else:
        if len(nodes) >= 2:
            relations.append({
                "source_label": nodes[0]["label"], "source_type": nodes[0]["type"],
                "target_label": nodes[1]["label"], "target_type": nodes[1]["type"],
                "relation_type": "UTILIZES", "properties": {}
            })
            
    return {"nodes": nodes, "relations": relations}
